% -------------------------------------------------------------------
%  Generated by MATLAB on 12-Mar-2025 16:29:46
%  MATLAB version: 23.2.0.2365128 (R2023b)
% -------------------------------------------------------------------
saveVarsMat = load('data1.mat');

NN_x_1 = saveVarsMat.NN_x_1; % <10001x3 double> 元素太多

x = saveVarsMat.x; % <3x10001 double> 元素太多

y_d = saveVarsMat.y_d; % <10001x1 double> 元素太多

clear saveVarsMat;
